#!/usr/bin/env python3
"""Build the Clallam County comparison guide from canonical campground records."""
import csv, html
from pathlib import Path

HERE=Path(__file__).resolve().parent; SITE=HERE.parents[1]; CSV=HERE.parent/'data/campgrounds.csv'
GROUPS=[
 ('National Park and Lake Crescent', ['fairholme-campground','heart-o-the-hills-campground','mora-campground','ozette-campground','sol-duc-campground','log-cabin-resort-rv-campground']),
 ('State forest, state park, and county camping', ['bear-creek-campground','lyre-river-campground','sadie-creek-campground','bogachiel-state-park','sequim-bay-state-park','dungeness-recreation-area','salt-creek-recreation-area']),
 ('Private campground records to compare', ['elwha-dam-rv-park','forks-101-rv-park','crescent-beach-rv-park','gilgal-oasis-rv-park'])]

def card(r):
 def e(v): return html.escape(str(v or ''))
 sites=f"{r['Number of RV campsites']} RV sites" if r['Number of RV campsites'] else 'Site count not confirmed'
 length=f"Up to {r['Max RV length']} ft" if r['Max RV length'] else 'Confirm rig fit'
 hookups={'0':'No hookups','1':'Electric','2':'Water + electric','3':'Full hookups'}.get(r['Hookups'],'Hookups not confirmed')
 return f'''<article class="camp"><img src="/assets/images/topo/{e(r['Slug'])}.jpg" alt="Topographic map around {e(r['Name'])}" loading="lazy"><div class="camp-body"><span class="camp-kicker">{e(r['Park Type'])}</span><h3>{e(r['Name'])}</h3><p>{e(r['Short Description'])}</p><div class="facts"><span>{e(sites)}</span><span>{e(length)}</span><span>{e(hookups)}</span><span>{e(r['Time from Seattle'])}</span></div><a class="camp-link" href="/campground/{e(r['Slug'])}">See campground details →</a></div></article>'''

def main():
 rows={r['Slug']:r for r in csv.DictReader(CSV.open(newline='',encoding='utf-8-sig'))}; count=sum(map(lambda x:len(x[1]),GROUPS))
 sections=''.join(f'<h2>{html.escape(title)}</h2><div class="camp-grid">'+''.join(card(rows[s]) for s in slugs)+'</div>' for title,slugs in GROUPS)
 doc=f'''<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{count} Clallam County RV Campgrounds Compared (2026)</title><meta name="description" content="Compare {count} Clallam County RV campgrounds by hookups, RV length, reservations, current status, and drive time from Seattle."><meta name="robots" content="index, follow"><link rel="canonical" href="https://westcoastrvcamping.com/field-notes/clallam-county-rv-camping"><meta property="og:type" content="article"><meta property="og:title" content="{count} Clallam County RV Campgrounds Compared"><meta property="og:description" content="Source-checked RV camping around Lake Crescent, Port Angeles, Sequim, Forks, and the north Olympic Peninsula."><meta property="og:image" content="https://westcoastrvcamping.com/assets/images/topo/log-cabin-resort-rv-campground.jpg"><meta property="og:url" content="https://westcoastrvcamping.com/field-notes/clallam-county-rv-camping"><script type="application/ld+json">{{"@context":"https://schema.org","@type":"Article","headline":"{count} Clallam County RV Campgrounds Compared (2026)","datePublished":"2026-09-11","dateModified":"2026-09-11","mainEntityOfPage":"https://westcoastrvcamping.com/field-notes/clallam-county-rv-camping","author":{{"@type":"Organization","name":"West Coast RV Camping"}},"publisher":{{"@type":"Organization","name":"West Coast RV Camping"}}}}</script><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600;700&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="../assets/nav.css?v=20260911"><link rel="stylesheet" href="../assets/tokens.css"><link rel="stylesheet" href="../assets/base.css"><link rel="stylesheet" href="../assets/footer.css"><style>
.hero{{background:var(--forest);color:#fff;padding:122px var(--gutter) 64px}}.hero-inner,.article{{max-width:980px;margin:auto}}.crumb{{display:flex;gap:8px;color:#b8c8be;font-size:12px;margin-bottom:24px}}.eyebrow{{color:var(--gold-light);text-transform:uppercase;letter-spacing:1.2px;font-weight:700;font-size:11px}}h1{{font-family:var(--font-display);font-size:clamp(36px,6vw,64px);line-height:1.05;margin:12px 0 18px}}.lede{{max-width:760px;color:#d4dfd8;font-size:clamp(16px,2vw,19px);line-height:1.65}}.byline{{margin-top:24px;color:#b8c8be;font-size:13px}}.article{{padding:clamp(44px,7vw,80px) var(--gutter)}}.intro,.section-copy{{max-width:780px;color:var(--text-mid);font-size:17px;line-height:1.75}}.quick{{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:32px 0 56px}}.quick div{{background:var(--parchment);border:1px solid var(--tan);border-radius:var(--r-lg);padding:18px}}.quick strong{{display:block;color:var(--forest);font-size:14px;margin-bottom:5px}}.quick span{{color:var(--text-muted);font-size:12px;line-height:1.45}}h2{{font-family:var(--font-display);color:var(--forest);font-size:clamp(27px,4vw,38px);margin:54px 0 20px}}.camp-grid{{display:grid;grid-template-columns:1fr 1fr;gap:20px}}.camp{{display:flex;flex-direction:column;border:1px solid var(--tan);border-radius:var(--r-xl);overflow:hidden;background:#fff;box-shadow:var(--shadow-sm)}}.camp img{{width:100%;aspect-ratio:2/1;object-fit:cover}}.camp-body{{display:flex;flex:1;flex-direction:column;padding:22px}}.camp-kicker{{color:var(--earth);text-transform:uppercase;letter-spacing:.9px;font-size:10px;font-weight:700}}.camp h3{{font-family:var(--font-display);color:var(--forest);font-size:22px;margin:7px 0 9px}}.camp p{{color:var(--text-mid);font-size:14px;line-height:1.62}}.facts{{display:flex;flex-wrap:wrap;gap:7px;margin:14px 0 18px}}.facts span{{background:var(--parchment);border-radius:999px;padding:6px 9px;font-size:11px;color:var(--text-mid)}}.camp-link{{align-self:flex-start;margin-top:auto;min-height:44px;padding:11px 16px;border-radius:999px;background:var(--forest);color:#fff;font-size:13px;font-weight:700}}.camp-link:hover{{background:var(--forest-mid)}}.note{{margin-top:48px;padding:24px;background:var(--gold-pale);border:1px solid var(--tan);border-radius:var(--r-xl);color:var(--text-mid);line-height:1.7}}@media(max-width:760px){{.quick,.camp-grid{{grid-template-columns:1fr 1fr}}}}@media(max-width:560px){{.hero{{padding-top:104px}}.quick,.camp-grid{{grid-template-columns:1fr}}.camp-body{{padding:19px}}}}
</style></head><body data-nav-cta-text="Browse Campgrounds →" data-nav-cta-url="/campgrounds"><header class="hero"><div class="hero-inner"><nav class="crumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><a href="/field-notes">Field Notes</a><span>/</span><span>Clallam County</span></nav><span class="eyebrow">Olympic Peninsula guide</span><h1>RV camping in Clallam County, Washington</h1><p class="lede">Compare {count} campground records around Lake Crescent, Port Angeles, Sequim, Forks, the Sol Duc corridor, and the Strait of Juan de Fuca.</p><p class="byline">Public-land facts reviewed September 11, 2026 · 16 minute read</p></div></header><main class="article"><p class="intro">Clallam County spans dry shoreline near Sequim, Lake Crescent, temperate forest around Forks, and the northwest coast. This guide brings the choices into one consistent view. The public operator layers have been checked against current DNR, National Park, Washington State Parks, and Clallam County sources. Private records remain in the comparison while their deeper operator review continues.</p><div class="quick"><div><strong>Best full-hookup lake base</strong><span>Log Cabin Resort has 31 RV sites and accepts rigs up to 35 feet.</span></div><div><strong>Best public hookups</strong><span>Sequim Bay has 15 full-hookup sites among 60 RV-capable campsites.</span></div><div><strong>Best small-rig solitude</strong><span>Lyre River pairs 11 first-come sites with a 20-foot trailer limit.</span></div><div><strong>Best county coast base</strong><span>Salt Creek combines 92 sites, utility choices, showers, trails, and tide pools.</span></div></div>{sections}<h2>How to choose</h2><p class="section-copy">Choose Log Cabin or Sol Duc when hookups matter. Fairholme is the classic Lake Crescent dry-camping base, while Mora puts you closest to Rialto Beach. Heart O’ the Hills works well for Port Angeles and Hurricane Ridge. Salt Creek and Dungeness add reservable county sites with showers; Sequim Bay adds full hookups. Bear Creek, Lyre River, and Sadie Creek are small first-come DNR choices for self-contained rigs, with seasonal status and road conditions worth checking before departure.</p><div class="note"><strong>Accuracy note:</strong> A campground-wide maximum can describe only a few pads. Open the campground page for the exact caveat, then confirm your assigned site with the operator. Drive times use a no-ferry Seattle baseline and round upward for towing. Temporary closures and fire restrictions can change after this review date.</div></main><script src="../assets/nav.js?v=20260911"></script><script src="../assets/footer.js?v=20260906d"></script></body></html>'''
 (SITE/'field-notes/clallam-county-rv-camping.html').write_text(doc,encoding='utf-8')
 print(f'Generated Clallam County guide with {count} campground records.')
if __name__=='__main__': main()
