#!/usr/bin/env python3
"""Build the Snohomish County RV comparison guide from canonical records."""
import csv, html, json
from pathlib import Path

HERE=Path(__file__).resolve().parent; SITE=HERE.parents[1]; CSV=HERE.parent/'data/campgrounds.csv'
GROUPS=[
 ('Lakes and Puget Sound',['flowing-lake-county-park','kayak-point-regional-park','wenberg-county-park']),
 ('River and mountain foothills',['river-meadows-county-park','squire-creek-park-campground','whitehorse-campground']),
 ('Utility stop in Monroe',['evergreen-state-fairgrounds-rv-2'])]

def card(r):
 e=lambda v:html.escape(str(v or ''))
 sites=f"{r['Number of RV campsites']} RV sites" if r['Number of RV campsites'] else 'RV count not confirmed'
 length=f"Up to {r['Max RV length']} ft" if r['Max RV length'] else 'Check site dimensions'
 hookups={'0':'No hookups','1':'Electric','2':'Water + electric','3':'Full hookups'}.get(r['Hookups'],'Hookups not confirmed')
 return f'''<article class="camp"><img src="/assets/images/topo/{e(r['Slug'])}.jpg" alt="Topographic map around {e(r['Name'])}" loading="lazy"><div class="camp-body"><span class="camp-kicker">{e(r['Park Type'])}</span><h3>{e(r['Name'])}</h3><p>{e(r['Short Description'])}</p><div class="facts"><span>{e(sites)}</span><span>{e(length)}</span><span>{e(hookups)}</span><span>{e(r['Time from Seattle'])}</span></div><a class="camp-link" href="/campground/{e(r['Slug'])}">See campground details →</a></div></article>'''

def main():
 rows={r['Slug']:r for r in csv.DictReader(CSV.open(newline='',encoding='utf-8-sig'))}
 sections=''.join(f'<h2>{html.escape(title)}</h2><div class="camp-grid">'+''.join(card(rows[s]) for s in slugs)+'</div>' for title,slugs in GROUPS)
 schema=json.dumps({'@context':'https://schema.org','@type':'Article','headline':'7 Snohomish County RV Campgrounds Compared (2026)','datePublished':'2026-09-12','dateModified':'2026-09-12','mainEntityOfPage':'https://westcoastrvcamping.com/field-notes/snohomish-county-rv-camping','author':{'@type':'Organization','name':'West Coast RV Camping'},'publisher':{'@type':'Organization','name':'West Coast RV Camping'}},separators=(',',':'))
 doc=f'''<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>7 Snohomish County RV Campgrounds Compared (2026)</title><meta name="description" content="Compare 7 Snohomish County RV campgrounds by hookups, RV fit, reservations, seasons, and drive time from Seattle."><meta name="robots" content="index, follow"><link rel="canonical" href="https://westcoastrvcamping.com/field-notes/snohomish-county-rv-camping"><meta property="og:type" content="article"><meta property="og:title" content="7 Snohomish County RV Campgrounds Compared"><meta property="og:description" content="Source-checked county camping from Puget Sound and Lake Goodwin to Darrington and Monroe."><meta property="og:image" content="https://westcoastrvcamping.com/assets/images/topo/kayak-point-regional-park.jpg"><meta property="og:url" content="https://westcoastrvcamping.com/field-notes/snohomish-county-rv-camping"><script type="application/ld+json">{schema}</script><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600;700&family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="../assets/nav.css?v=20260911"><link rel="stylesheet" href="../assets/tokens.css"><link rel="stylesheet" href="../assets/base.css"><link rel="stylesheet" href="../assets/footer.css"><style>
.hero{{background:var(--forest);color:#fff;padding:122px var(--gutter) 64px}}.hero-inner,.article{{max-width:980px;margin:auto}}.crumb{{display:flex;flex-wrap:wrap;gap:8px;color:#b8c8be;font-size:12px;margin-bottom:24px}}.eyebrow{{color:var(--gold-light);text-transform:uppercase;letter-spacing:1.2px;font-weight:700;font-size:11px}}h1{{font-family:var(--font-display);font-size:clamp(36px,6vw,64px);line-height:1.05;margin:12px 0 18px}}.lede{{max-width:760px;color:#d4dfd8;font-size:clamp(16px,2vw,19px);line-height:1.65}}.byline{{margin-top:24px;color:#b8c8be;font-size:13px}}.article{{padding:clamp(44px,7vw,80px) var(--gutter)}}.intro,.section-copy{{max-width:800px;color:var(--text-mid);font-size:17px;line-height:1.75}}.quick{{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:32px 0 56px}}.quick div{{background:var(--parchment);border:1px solid var(--tan);border-radius:var(--r-lg);padding:18px}}.quick strong{{display:block;color:var(--forest);font-size:14px;margin-bottom:5px}}.quick span{{color:var(--text-muted);font-size:12px;line-height:1.45}}h2{{font-family:var(--font-display);color:var(--forest);font-size:clamp(27px,4vw,38px);margin:54px 0 20px}}.camp-grid{{display:grid;grid-template-columns:1fr 1fr;gap:20px}}.camp{{display:flex;flex-direction:column;border:1px solid var(--tan);border-radius:var(--r-xl);overflow:hidden;background:#fff;box-shadow:var(--shadow-sm)}}.camp img{{width:100%;aspect-ratio:2/1;object-fit:cover}}.camp-body{{display:flex;flex:1;flex-direction:column;padding:22px}}.camp-kicker{{color:var(--earth);text-transform:uppercase;letter-spacing:.9px;font-size:10px;font-weight:700}}.camp h3{{font-family:var(--font-display);color:var(--forest);font-size:22px;margin:7px 0 9px}}.camp p{{color:var(--text-mid);font-size:14px;line-height:1.62}}.facts{{display:flex;flex-wrap:wrap;gap:7px;margin:14px 0 18px}}.facts span{{background:var(--parchment);border-radius:999px;padding:6px 9px;font-size:11px;color:var(--text-mid)}}.camp-link{{align-self:flex-start;margin-top:auto;min-height:44px;padding:11px 16px;border-radius:999px;background:var(--forest);color:#fff;font-size:13px;font-weight:700}}.camp-link:hover{{background:var(--forest-mid)}}.note{{margin-top:48px;padding:24px;background:var(--gold-pale);border:1px solid var(--tan);border-radius:var(--r-xl);color:var(--text-mid);line-height:1.7}}@media(max-width:760px){{.quick{{grid-template-columns:1fr}}.camp-grid{{grid-template-columns:1fr 1fr}}}}@media(max-width:560px){{.hero{{padding-top:104px}}.camp-grid{{grid-template-columns:1fr}}.camp-body{{padding:19px}}}}
</style></head><body data-nav-cta-text="Browse Campgrounds →" data-nav-cta-url="/campgrounds"><header class="hero"><div class="hero-inner"><nav class="crumb" aria-label="Breadcrumb"><a href="/">Home</a><span>/</span><a href="/field-notes">Field Notes</a><span>/</span><span>Snohomish County</span></nav><span class="eyebrow">Puget Sound and Cascade foothills</span><h1>RV camping in Snohomish County, Washington</h1><p class="lede">Compare seven county-operated choices around Lake Goodwin, Puget Sound, the Stillaguamish River, Darrington, Monroe, and the Cascade foothills.</p><p class="byline">County facility facts reviewed September 12, 2026 · 9 minute read</p></div></header><main class="article"><p class="intro">Snohomish County's campground system spans waterfront weekend parks, simple forest sites, full-utility mountain camping, and a seasonal fairgrounds RV lot. This guide uses current county pages and campground maps. When the county publishes only site-by-site pad dimensions, the listing asks you to check the chosen site instead of inventing one park-wide maximum.</p><div class="quick"><div><strong>Best full utilities</strong><span>Whitehorse has 15 full-utility RV or equestrian sites near Darrington.</span></div><div><strong>Best saltwater setting</strong><span>Kayak Point pairs 30 partial-utility sites with Puget Sound shoreline and a fishing pier.</span></div><div><strong>Best easy utility stop</strong><span>Evergreen RV-2 has 117 seasonal water-and-electric sites close to Monroe services.</span></div></div>{sections}<h2>How to choose</h2><p class="section-copy">Choose Flowing Lake for a close-to-Seattle lake weekend, Kayak Point for Puget Sound, or Wenberg for the broadest lake facilities and utility mix. River Meadows and Squire Creek trade hookups for quieter river and forest settings. Whitehorse provides the strongest campground utilities near Darrington. Evergreen RV-2 works as a seasonal staging stop, with fair-date exclusions and a seven-night maximum.</p><div class="note"><strong>Accuracy note:</strong> Snohomish County utility types and seasons vary by loop and sometimes by site. Read the live reservation description before choosing a pad. Reservations close three days before arrival, and weekend reservations normally require Friday and Saturday. Drive times use an all-road Seattle baseline and round upward for towing; traffic can change them substantially.</div></main><script src="../assets/nav.js?v=20260911"></script><script src="../assets/footer.js?v=20260906d"></script></body></html>'''
 (SITE/'field-notes/snohomish-county-rv-camping.html').write_text(doc,encoding='utf-8')
 print('Generated Snohomish County guide with 7 campground records.')

if __name__=='__main__': main()
