#!/usr/bin/env python3
"""Publish the reviewed Snohomish County private and tribal campground layer."""
import csv, json
from pathlib import Path

HERE = Path(__file__).resolve().parent
MASTER = HERE / "data/campgrounds.csv"
EVIDENCE = HERE / "verification-evidence.json"
COVERAGE = HERE / "coverage-inventory.json"
REVIEWS = HERE / "snohomish-private-location-reviews.json"
CHECKED = "2026-09-12"

ANGEL = "https://rvwinds.com/"
ANGEL_SITES = "https://rvwinds.com/home/sites-yurts/"
PLEASANT = "https://www.lakepleasantrv.com/rates/"
MAPLE = "https://maplegrovervresort.com/our-parks-sites/"
MAPLE_FAQ = "https://maplegrovervresort.com/frequently-asked-questions/"
CASCADE = "https://www.cascadesrvresort.com/"
CASCADE_AMENITIES = "https://www.cascadesrvresort.com/amenities/"
THUNDERBIRD = "https://thousandtrails.com/washington/thunderbird-rv-camping-resort/directions"
EMERALD = "https://emeraldspringsrv.com/"
EMERALD_DIRECTIONS = "https://emeraldspringsrv.com/logistics"
GOODWIN = "https://www.lakegoodwinresort.com/rental-rates/"
GOODWIN_WELCOME = "https://www.lakegoodwinresort.com/welcome.html"
LAKE_KI = "https://www.lakekiresort.com/"
MONROE = "https://www.monroewa.gov/865/FAQs"
REGIONAL = "https://www.discoversnohomishcounty.com/where-to-stay/"

BASE = {"Park Type": "Private Campground", "Archived": "false", "Draft": "false", "RV Access": "yes", "Cell coverage": "0"}
ROWS = {
    "angel-of-the-winds-rv-resort": {**BASE, "Park Type": "Tribal Campground", "Name": "Angel of the Winds RV Resort", "Nearest town": "Arlington, WA", "Number of RV campsites": "178", "Max RV length": "", "Maneuverability": "1", "Site surface type": "Paved", "Hookups": "3", "Dump station on site": "", "Generator policy": "", "Amenities: Toilets": "Flush toilets", "Amenities: Showers": "true", "Amenities: Drinking water": "true", "Amenities: Fire pits": "", "Reservation window": "Book current RV-site availability online; maximum stay is 14 days", "Reservation website": ANGEL, "Short Description": "Stillaguamish Tribe-owned resort with 178 full-hookup concrete RV sites, long pull-through and back-in pads, a pool, clubhouse, laundry, and family recreation.", "Long description": "Angel of the Winds RV Resort is owned by the Stillaguamish Tribe of Indians and sits west of Arlington near I-5. The operator lists 178 full-hookup spaces: 154 pull-through sites with 68-foot pads and 24 back-in sites with 75-foot pads. Every RV site has water, sewer, 20/30/50-amp power, a concrete pad, picnic table, and lawn. The clubhouse, seasonal pool, laundry, dog park, playground, pickleball, mini golf, store, barbecue shelters, and casino shuttle support longer family stays. The published pad lengths are not presented as universal RV limits, so confirm total equipment length while booking.", "Amenities summary": "Full hookups at every concrete RV site, plus clubhouse, pool, showers, laundry, store, dog park, playground, pickleball, mini golf, barbecue shelters, and casino shuttle.", "Site Recommendations": "Choose a 68-foot pull-through or 75-foot back-in pad based on your full vehicle combination. The park accepts RVs rather than tents and limits stays to 14 days.", "Access note": "Use the operator-published Dahl Road entrance west of I-5. The RV resort is separate from the nearby casino complex.", "Access source": ANGEL, "Things to do for families": "Swim in the seasonal pool\nPlay mini golf\nUse the playground\nPlay pickleball\nVisit the clubhouse\nTake the shuttle to the casino resort", "Things to do for families summary": "A high-service tribal RV resort with several on-site recreation choices and quick I-5 access.", "Nearby nature & parks": "The resort sits in the Stillaguamish River lowlands between Arlington and Stanwood, with day trips toward Port Susan, Lake Goodwin, and the North Cascades foothills.", "Hiking": "false", "Fishing": "false", "Swimming": "true", "Kayaking/Paddling": "false", "Beach & Tide Pools": "false", "Boating": "false", "Playground": "true", "Nearby campgrounds": "emerald-springs-rv-park;lake-ki-rv-resort;lake-goodwin-resort;wenberg-county-park"},
    "lake-pleasant-rv-park": {**BASE, "Name": "Lake Pleasant RV Park", "Nearest town": "Bothell, WA", "Number of RV campsites": "184", "Max RV length": "", "Maneuverability": "1", "Site surface type": "Paved", "Hookups": "3", "Dump station on site": "", "Generator policy": "", "Amenities: Toilets": "Flush toilets", "Amenities: Showers": "true", "Amenities: Drinking water": "true", "Amenities: Fire pits": "false", "Reservation window": "Daily sites are offered year-round with a 14-day cap; book current availability online", "Reservation website": PLEASANT, "Short Description": "Wooded Bothell RV park with 184 paved back-in and pull-through sites, full 30/50-amp hookups, five private shower houses, and year-round daily stays.", "Long description": "Lake Pleasant RV Park provides a wooded RV base in Bothell, about 17 road miles from central Seattle. The operator lists 184 paved back-in and pull-through sites with picnic tables and full water, sewer, and 30/50-amp electric hookups. Five private shower houses, propane, pet-friendly policies, trails, and a small lake area distinguish it from a typical urban RV lot. Daily sites are offered year-round and are capped at 14 days; seasonal monthly inventory follows a separate schedule. The operator does not publish a campground-wide maximum RV length.", "Amenities summary": "Paved full-hookup sites with 30/50-amp service, picnic tables, five private shower houses, propane, trails, and a wildlife lake area.", "Site Recommendations": "Use the booking system to select a back-in or pull-through site and confirm exact pad fit. Nightly reservations are limited to 14 days and the park does not offer weekly rates.", "Access note": "Use the named RV park entrance on Bothell Everett Highway near Canyon Park.", "Access source": PLEASANT, "Things to do for families": "Walk the wooded trails\nExplore the lake area\nVisit Bothell parks\nTake a Seattle day trip\nVisit Woodinville\nUse nearby city services", "Things to do for families summary": "The closest verified full-hookup option in this county batch, with woods and a lake inside the Bothell park.", "Nearby nature & parks": "The park surrounds a small lake and wooded paths in Bothell, with the Sammamish River corridor and Woodinville nearby.", "Hiking": "true", "Fishing": "false", "Swimming": "false", "Kayaking/Paddling": "false", "Beach & Tide Pools": "false", "Boating": "false", "Playground": "false", "Nearby campgrounds": "maple-grove-rv-resort;flowing-lake-county-park;evergreen-state-fairgrounds-rv-2;thousand-trails-thunderbird"},
    "maple-grove-rv-resort": {**BASE, "Name": "Maple Grove RV Resort", "Nearest town": "Everett, WA", "Number of RV campsites": "87", "Max RV length": "", "Maneuverability": "1", "Site surface type": "Paved", "Hookups": "3", "Dump station on site": "", "Generator policy": "", "Amenities: Toilets": "Flush toilets", "Amenities: Showers": "true", "Amenities: Drinking water": "true", "Amenities: Fire pits": "false", "Reservation window": "Daily and weekly reservations open up to 3 months in advance", "Reservation website": "https://maplegrovervresort.com/contact-maple-grove-rv-park/", "Short Description": "Everett resort with 87 numbered sites, concrete 55-foot pull-through and 40-foot perimeter pads, full hookups, Wi-Fi, cable, and short-term reservations.", "Long description": "Maple Grove RV Resort is an 87-site urban RV park on Highway 99 in Everett. The operator describes 55-by-22.5-foot pull-through pads, 40-by-22.5-foot perimeter back-ins, and 27-foot split sites. Its FAQ says all sites have full water, sewer, and electric hookups, while the detailed site map also identifies a water-only configuration; guests should confirm the utility type assigned in the reservation. Full-hookup configurations include 20/30/50-amp or 20/30-amp power, Wi-Fi, cable, telephone, water, and sewer. Daily and weekly reservations can be made up to three months ahead. Pad dimensions vary and are not a universal RV maximum.", "Amenities summary": "Concrete site configurations with water, sewer, electric, Wi-Fi, cable, telephone, landscaped space, and a service building; verify any water-only inventory when reserving.", "Site Recommendations": "Use a 55-foot pull-through for the largest combinations, a 40-foot perimeter site for many large RVs, or a 27-foot split site for smaller equipment. Confirm both fit and utility type.", "Access note": "Use the operator-linked Highway 99 entrance in Everett; this resort is distinct from similarly named RV businesses.", "Access source": "https://maplegrovervresort.com/contact-maple-grove-rv-park/", "Things to do for families": "Visit Everett waterfront parks\nExplore Paine Field attractions\nTake a Seattle day trip\nVisit Mukilteo\nUse nearby shopping and dining", "Things to do for families summary": "A paved full-service Everett base suited to city stops and north Puget Sound day trips.", "Nearby nature & parks": "The resort is in south Everett, within driving distance of Puget Sound shoreline parks in Mukilteo and the Snohomish River estuary.", "Hiking": "false", "Fishing": "false", "Swimming": "false", "Kayaking/Paddling": "false", "Beach & Tide Pools": "false", "Boating": "false", "Playground": "false", "Nearby campgrounds": "lake-pleasant-rv-park;flowing-lake-county-park;kayak-point-regional-park;evergreen-state-fairgrounds-rv-2"},
    "cascade-views-rv-resort": {**BASE, "Name": "Cascade Views RV Resort", "Nearest town": "Sultan, WA", "Number of RV campsites": "", "Max RV length": "", "Maneuverability": "1", "Site surface type": "Paved", "Hookups": "", "Dump station on site": "", "Generator policy": "", "Amenities: Toilets": "Flush toilets", "Amenities: Showers": "true", "Amenities: Drinking water": "", "Amenities: Fire pits": "false", "Reservation window": "Call the resort for current nightly, weekly, or monthly availability", "Reservation website": "https://www.cascadesrvresort.com/rates/", "Short Description": "Family-run Sultan resort with concrete RV pads, 90- and 45-foot pull-through choices, showers, laundry, internet, propane, a dog park, and phone reservations.", "Long description": "Cascade Views RV Resort is a family-run private park east of Sultan near US 2. The operator lists 90-foot pull-through, 45-foot pull-through, and 45-foot back-in site types, each with a concrete RV pad, turf area, and gravel picnic space. High-speed internet, showers, laundry, propane, and a fenced dog park are available. The current operator pages advertise nightly, weekly, and monthly stays but do not specify the utility hookup level or a universal maximum RV length. This listing leaves both claims unfilled and directs guests to confirm them by phone.", "Amenities summary": "Concrete RV pads with turf and picnic areas, plus high-speed internet, showers, laundry, propane, and a fenced dog park; utility hookup level is not published.", "Site Recommendations": "Ask for a 90-foot pull-through when total combination length needs the most room. Confirm electric, water, sewer, and current fire rules directly before booking.", "Access note": "Use the operator-embedded map point at the 339th Avenue SE address east of Sultan.", "Access source": "https://www.cascadesrvresort.com/contact-us/", "Things to do for families": "Explore Sultan\nRaft the Skykomish River with a permitted outfitter\nHike in the Cascade foothills\nTake a Stevens Pass day trip\nUse the fenced dog park", "Things to do for families summary": "A roomy US 2 corridor base for the Skykomish Valley and Cascade foothill trips.", "Nearby nature & parks": "The resort sits in the Skykomish River valley below the Cascade foothills, with hiking, rafting, and Stevens Pass trips along US 2.", "Hiking": "true", "Fishing": "true", "Swimming": "false", "Kayaking/Paddling": "true", "Beach & Tide Pools": "false", "Boating": "false", "Playground": "false", "Nearby campgrounds": "thousand-trails-thunderbird;evergreen-state-fairgrounds-rv-2;flowing-lake-county-park;turlo-campground"},
    "thousand-trails-thunderbird": {**BASE, "Name": "Thousand Trails Thunderbird", "Nearest town": "Monroe, WA", "Number of RV campsites": "92", "Max RV length": "", "Maneuverability": "2", "Site surface type": "Mixed", "Hookups": "", "Dump station on site": "", "Generator policy": "", "Amenities: Toilets": "Flush toilets", "Amenities: Showers": "true", "Amenities: Drinking water": "", "Amenities: Fire pits": "", "Reservation window": "Book RV sites online as a member or guest; peak-season stays are limited to 14 days per site", "Reservation website": "https://newbook.thousandtrails.com/thunderbird-rv-camping-resort/?force_category_type_id=2", "Short Description": "Year-round 92-site resort on the Skykomish River with guest booking, a pool and hot tub, showers, laundry, mini golf, fishing, trails, and family recreation.", "Long description": "Thousand Trails Thunderbird is a 92-site year-round RV and camping resort on the Skykomish River outside Monroe. The operator explicitly allows nonmembers to book as guests and offers RV sites, tent sites, and lodging. Amenities include restrooms and showers, laundry, a clubhouse, pool, hot tub, mini golf, playground, dog park, trails, fishing, sports courts, picnic areas, and Wi-Fi. The current operator page and resort map do not publish a campground-wide RV length or clear utility hookup level, so this record does not turn those unknowns into claims. From April 15 through September 15, reservations are limited to 14 days per site, although consecutive stays may move between sites.", "Amenities summary": "Riverfront resort with restrooms, showers, laundry, clubhouse, pool, hot tub, mini golf, playground, dog park, trails, fishing, sports courts, picnic areas, and Wi-Fi.", "Site Recommendations": "Enter exact RV dimensions in the operator booking flow and confirm the assigned site's utilities. Peak-season consecutive stays may require moving sites.", "Access note": "Use the operator-published GPS point and Ben Howard Road entrance southeast of Monroe.", "Access source": THUNDERBIRD, "Things to do for families": "Swim in the pool\nPlay mini golf\nFish the Skykomish River\nUse the playground\nWalk resort trails\nExplore Monroe", "Things to do for families summary": "The broadest on-site recreation package in the county, directly beside the Skykomish River.", "Nearby nature & parks": "The resort fronts the Skykomish River near Monroe, with the lower Cascade foothills and US 2 recreation corridor nearby.", "Hiking": "true", "Fishing": "true", "Swimming": "true", "Kayaking/Paddling": "false", "Beach & Tide Pools": "false", "Boating": "false", "Playground": "true", "Nearby campgrounds": "evergreen-state-fairgrounds-rv-2;cascade-views-rv-resort;flowing-lake-county-park;lake-pleasant-rv-park"},
    "emerald-springs-rv-park": {**BASE, "Name": "Emerald Springs RV Park", "Nearest town": "Arlington, WA", "Number of RV campsites": "", "Max RV length": "", "Maneuverability": "1", "Site surface type": "Gravel", "Hookups": "3", "Dump station on site": "", "Generator policy": "", "Amenities: Toilets": "", "Amenities: Showers": "", "Amenities: Drinking water": "true", "Amenities: Fire pits": "", "Reservation window": "Call for current nightly, weekly, or extended-stay availability", "Reservation website": EMERALD, "Short Description": "Country-setting Arlington RV park with level full-hookup sites, 30/50-amp power, laundry, pet-friendly rules, and nightly through long-term stays.", "Long description": "Emerald Springs RV Park serves the Arlington and Marysville area from a quiet setting east of I-5. Every site has city water, direct sewer, and 30/50-amp electric hookups. The operator offers nightly, weekly, and longer stays, plus on-site laundry and pet-friendly policies. It describes large level spaces for a range of RV sizes but publishes neither a current site count nor a numeric maximum. Public restroom and shower availability is also not stated, so the listing leaves those amenities unconfirmed.", "Amenities summary": "Level full-hookup sites with city water, sewer, 30/50-amp electric service, laundry, and pet-friendly rules; public restrooms and showers are not confirmed.", "Site Recommendations": "Call with exact dimensions and desired stay length. Confirm whether public restroom or shower access is needed because the operator does not list those amenities.", "Access note": "From I-5 exit 206, follow the operator directions east on 172nd Street and south on 51st Avenue NE; the park is on the right.", "Access source": EMERALD_DIRECTIONS, "Things to do for families": "Explore Arlington\nVisit nearby shopping and dining\nTake a Lake Goodwin day trip\nVisit the Stillaguamish River valley\nUse the on-site laundry", "Things to do for families summary": "A simple full-hookup base near I-5 for Arlington, Marysville, and north county errands.", "Nearby nature & parks": "The park sits in rural lowlands between Arlington and Marysville, within driving distance of Lake Goodwin and the Stillaguamish River.", "Hiking": "false", "Fishing": "false", "Swimming": "false", "Kayaking/Paddling": "false", "Beach & Tide Pools": "false", "Boating": "false", "Playground": "false", "Nearby campgrounds": "angel-of-the-winds-rv-resort;lake-ki-rv-resort;lake-goodwin-resort;wenberg-county-park"},
    "lake-goodwin-resort": {**BASE, "Name": "Lake Goodwin Resort", "Nearest town": "Stanwood, WA", "Number of RV campsites": "", "Max RV length": "", "Maneuverability": "2", "Site surface type": "Mixed", "Hookups": "3", "Dump station on site": "", "Generator policy": "", "Amenities: Toilets": "Flush toilets", "Amenities: Showers": "true", "Amenities: Drinking water": "true", "Amenities: Fire pits": "true", "Reservation window": "Call for daily or weekly RV reservations; two-night minimum for advance reservations", "Reservation website": GOODWIN, "Short Description": "Year-round family resort on Lake Goodwin with daily RV sites, most with water, 30/50-amp power and septic, plus beach, docks, showers, laundry, and a store.", "Long description": "Lake Goodwin Resort is a year-round private campground on the north shore of Lake Goodwin. The operator offers regular, beach, pull-through, and combo RV/tent choices at daily and weekly rates. Most RV sites have water, 30/50-amp electric, and septic hookups; all sites have a picnic table and fire pit. A sandy beach, docks, small-craft launch, store, gas, propane, restrooms, showers, laundry, playground, and sports areas support family lake stays. The operator does not publish a current RV-site count or universal maximum. Advance reservations require at least two nights, with a three-night minimum on holiday weekends.", "Amenities summary": "Most RV sites have water, 30/50-amp electric, and septic, with picnic tables and fire pits; resort facilities include beach, docks, launch, store, gas, propane, showers, laundry, and playground.", "Site Recommendations": "Ask whether the assigned regular, beach, pull-through, or combo site has all three utilities. Confirm total rig length and current lake-access rules before arrival.", "Access note": "Use the named resort entrance at the operator-published Lakewood Road address on the north side of Lake Goodwin.", "Access source": GOODWIN, "Things to do for families": "Swim at the sandy beach\nFish Lake Goodwin\nKayak or paddle\nUse the playground\nPlay basketball or volleyball\nLaunch a small watercraft", "Things to do for families summary": "A private Lake Goodwin resort with shore access, family recreation, transient RV choices, and on-site services.", "Nearby nature & parks": "The resort is on Lake Goodwin's north shore, about a mile from Wenberg County Park and near the Seven Lakes area.", "Hiking": "false", "Fishing": "true", "Swimming": "true", "Kayaking/Paddling": "true", "Beach & Tide Pools": "false", "Boating": "true", "Playground": "true", "Nearby campgrounds": "lake-ki-rv-resort;wenberg-county-park;angel-of-the-winds-rv-resort;kayak-point-regional-park"},
    "lake-ki-rv-resort": {**BASE, "Name": "Lake Ki RV Resort", "Nearest town": "Arlington, WA", "Number of RV campsites": "", "Max RV length": "", "Maneuverability": "2", "Site surface type": "Mixed", "Hookups": "3", "Dump station on site": "", "Generator policy": "", "Amenities: Toilets": "", "Amenities: Showers": "", "Amenities: Drinking water": "true", "Amenities: Fire pits": "true", "Reservation window": "Book daily stays online up to 10 days; monthly sites use a separate application", "Reservation website": LAKE_KI, "Short Description": "Lakefront Arlington resort with daily full-hookup RV sites, private swimming beach, fishing docks, small-boat launch, laundry, fire pits, and online booking.", "Long description": "Lake Ki RV Resort offers daily and monthly RV sites on the shore of Lake Ki west of Arlington. Current operator material confirms full RV hookups, fire pits, picnic tables, laundry, storage for monthly guests, a private swimming beach, fishing docks, a small-boat launch, playground space, and pet-friendly policies. Daily sites can be booked immediately online for stays up to 10 days; monthly sites use a separate application. The operator does not publish a site count, campground-wide maximum RV length, or public restroom and shower details, so those remain unclaimed.", "Amenities summary": "Full RV hookups, fire pits, picnic tables, laundry, private swimming beach, fishing docks, small-boat launch, playground space, and pet-friendly policies.", "Site Recommendations": "Use the daily booking flow for stays up to 10 days and enter exact equipment details. Confirm pad fit and restroom or shower access before relying on them.", "Access note": "Use the operator-linked named campground point on Lakewood Road along the north shore of Lake Ki.", "Access source": LAKE_KI, "Things to do for families": "Swim at the private beach\nFish from the docks\nKayak or paddle\nUse the playground areas\nLaunch a small boat\nExplore the Seven Lakes area", "Things to do for families summary": "A compact lakefront RV stay with full hookups, swimming, fishing, and paddling west of Arlington.", "Nearby nature & parks": "Lake Ki is a 100-acre lake in the Seven Lakes area, immediately east of Lake Goodwin and near Wenberg County Park.", "Hiking": "false", "Fishing": "true", "Swimming": "true", "Kayaking/Paddling": "true", "Beach & Tide Pools": "false", "Boating": "true", "Playground": "true", "Nearby campgrounds": "lake-goodwin-resort;wenberg-county-park;angel-of-the-winds-rv-resort;emerald-springs-rv-park"}
}

SOURCES = {
    "angel-of-the-winds-rv-resort": [(ANGEL, "Angel of the Winds RV Resort", "Operator confirms tribal resort identity, address, transient operation, and amenities."), (ANGEL_SITES, "Angel of the Winds RV Resort", "Operator publishes 178 spaces, site layouts, pad lengths, and full utility details.")],
    "lake-pleasant-rv-park": [(PLEASANT, "Lake Pleasant RV Park", "Operator publishes year-round daily booking, 184 sites, full hookups, surfaces, and amenities.")],
    "maple-grove-rv-resort": [(MAPLE, "Maple Grove RV Resort", "Operator publishes 87 numbered sites, configurations, dimensions, and utility details."), (MAPLE_FAQ, "Maple Grove RV Resort", "Operator confirms short-term booking and full-hookup availability.")],
    "cascade-views-rv-resort": [(CASCADE, "Cascade Views RV Resort", "Operator confirms active transient RV operation, address, concrete pads, and reservation method."), (CASCADE_AMENITIES, "Cascade Views RV Resort", "Operator publishes pad lengths and amenities but does not state utility hookup level.")],
    "thousand-trails-thunderbird": [(THUNDERBIRD, "Thousand Trails", "Operator confirms 92 year-round sites, guest booking, GPS point, stay rules, and amenities.")],
    "emerald-springs-rv-park": [(EMERALD, "Emerald Springs RV Park", "Operator confirms nightly and weekly stays, full hookups, laundry, and no numeric RV limit."), (EMERALD_DIRECTIONS, "Emerald Springs RV Park", "Operator publishes the address and turn-by-turn arrival directions.")],
    "lake-goodwin-resort": [(GOODWIN, "Lake Goodwin Resort", "Operator publishes current daily and weekly RV rates, reservation rules, and address."), (GOODWIN_WELCOME, "Lake Goodwin Resort", "Operator describes most-site utilities, RV types, lake access, and amenities.")],
    "lake-ki-rv-resort": [(LAKE_KI, "Lake Ki RV Resort", "Operator confirms daily online booking, full hookups, address, lake recreation, and amenities.")]
}

def duration(minutes):
    hours, mins = divmod(minutes, 60)
    if not hours:
        return f"~{mins} min from Seattle"
    return f"~{hours} hr {mins} min from Seattle" if mins else f"~{hours} hr from Seattle"

def source(url, publisher, note):
    return {"url": url, "publisher": publisher, "source_family": "snohomish-private-review", "evidence": note}

def main():
    reviews = {r["slug"]: r for r in json.loads(REVIEWS.read_text())["reviews"]}
    with MASTER.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle); fields = list(reader.fieldnames or []); rows = list(reader)
    by = {r["Slug"]: r for r in rows}
    for slug, data in ROWS.items():
        review = reviews[slug]
        row = by.get(slug, {field: "" for field in fields})
        row.update(data)
        row.update({
            "Slug": slug, "Data last updated": CHECKED,
            "Topographic background image": f"https://westcoastrvcamping.com/assets/images/topo/{slug}.jpg",
            "Time from Seattle": duration(review["display_minutes"]),
            "Drive Time Band": "under-1hr" if review["display_minutes"] < 60 else "1-2hrs",
            "Drive Time Minutes": str(review["display_minutes"]), "Address": review["address"],
            "Google Maps Link": f"https://www.google.com/maps?q={review['latitude']:.7f},{review['longitude']:.7f}",
            "State Map": f"/assets/images/svg/{slug}.svg", "Access checked": CHECKED,
            "Latitude": f"{review['latitude']:.7f}", "Longitude": f"{review['longitude']:.7f}",
            "Coordinates source": review["coordinate_source"], "Coordinates checked": CHECKED,
            "Coordinate precision": review["precision"], "Drive distance miles": str(review["distance_miles"]),
            "Drive route minutes": str(review["observed_route_minutes"]), "Drive time origin": "Seattle, Washington",
            "Drive time source": f"https://router.project-osrm.org/route/v1/driving/-122.3321,47.6062;{review['longitude']:.7f},{review['latitude']:.7f}?overview=false",
            "Drive time checked": CHECKED, "Drive time note": review["route_note"]
        })
        if slug not in by: rows.append(row)
        by[slug] = row
    with MASTER.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, lineterminator="\n"); writer.writeheader(); writer.writerows(rows)

    coverage = json.loads(COVERAGE.read_text()); coverage["updated_on"] = CHECKED
    coverage["sections"] = [s for s in coverage["sections"] if s.get("id") != "snohomish-private-tribal"]
    coverage["sections"].append({
        "id": "snohomish-private-tribal", "name": "Snohomish private and tribal campgrounds", "status": "complete",
        "inventory_sources": [REGIONAL, MONROE, ANGEL, PLEASANT, MAPLE, CASCADE, THUNDERBIRD, EMERALD, GOODWIN, LAKE_KI],
        "candidates": [
            *[{"name": ROWS[s]["Name"], "slug": s, "decision": "included_new", "reason": "Current operator material explicitly supports transient RV stays; unsupported facts remain unclaimed."} for s in ROWS],
            {"name": "Eagle Park RV Park", "decision": "deferred", "reason": "The City of Monroe still lists it, but no stable current operator page resolves the active site count, utilities, and transient reservation method."},
            {"name": "Cedar Grove Shores RV Park", "decision": "deferred", "reason": "Older directories identify an RV park, but no stable current operator source supports transient booking facts."},
            {"name": "Lakeside RV Park Everett", "decision": "excluded", "reason": "The current operator markets long-term stays and does not publish transient campground booking."},
            {"name": "Gold Bar Nature Trails", "decision": "excluded", "reason": "This is a gated member-owned camping community rather than public transient inventory."},
            {"name": "Port Susan Camping Club", "decision": "excluded", "reason": "This is a membership camping club rather than public transient inventory."},
            {"name": "The Landing at Index", "decision": "excluded", "reason": "The current operator describes tent-focused access on a rough logging road and does not support conventional RV access."},
            {"name": "Smokey Point Mobile Home and RV Park", "decision": "excluded", "reason": "Current evidence supports residential or extended-stay use rather than a public transient campground."},
            {"name": "Twin Cedars RV Park", "decision": "excluded", "reason": "Current evidence supports residential or extended-stay use rather than a public transient campground."},
            {"name": "Snohomish RV and Mobile Home Park", "decision": "excluded", "reason": "Current evidence supports residential or extended-stay use rather than a public transient campground."}
        ]
    })
    COVERAGE.write_text(json.dumps(coverage, indent=2) + "\n")

    evidence = json.loads(EVIDENCE.read_text()); affected = set(ROWS)
    evidence["observations"] = [o for o in evidence["observations"] if not (o.get("slug") in affected and o.get("source_family") == "snohomish-private-review")]
    for slug in affected:
        row = by[slug]; sources = [source(*s) for s in SOURCES[slug]]
        values = [("operating_status", "current"), ("rv_access", True), ("reservation_method", row["Reservation window"]), ("hookups", int(row["Hookups"]) if row["Hookups"] else None), ("max_rv_length", int(row["Max RV length"]) if row["Max RV length"] else None)]
        for field, value in values:
            unknown = value is None
            summary = (f"Current operator material does not publish {field.replace('_', ' ')}; the public record intentionally labels it unconfirmed." if unknown else f"Current operator material supports {field.replace('_', ' ')}.")
            evidence["observations"].append({"slug": slug, "field": field, "status": "supported", "checked_on": CHECKED, "summary": summary, "proposed_value": value, "source_family": "snohomish-private-review", "sources": sources})
    EVIDENCE.write_text(json.dumps(evidence, indent=2) + "\n")
    print(f"Completed Snohomish private/tribal phase: added {len(ROWS)} campgrounds and documented 9 excluded or deferred candidates. Dataset now has {len(rows)} records.")

if __name__ == "__main__": main()
