#!/usr/bin/env python3
"""Publish the reviewed Clallam County private and tribal campground layer."""
import csv, json
from pathlib import Path

HERE=Path(__file__).resolve().parent
MASTER=HERE/'data/campgrounds.csv'; EVIDENCE=HERE/'verification-evidence.json'; COVERAGE=HERE/'coverage-inventory.json'
REVIEWS=HERE/'clallam-private-location-reviews.json'; CHECKED='2026-09-11'
QUIL='https://quileuteoceanside.com/277695-2/'
QUIL_BOOK='https://online.rezexpert.com/book?business_code=4349'
HOBUCK='https://hobuckbeachresort.com/rv-camping/'
CAPE='https://cape-resort.com/rv-tent-camping/'
MASON='https://www.masonsresort.com/ways-to-stay/'
ANGLERS='https://www.anglershideaway.net/'
ANGLERS_BOOK='https://bookings.rmscloud.com/Search/Index/19975/1/'
THREE='https://forkslodging.net/3-rivers-resort/rv-and-camp-sites/'
MAKAH='https://makah.com/business/'
FORKS='https://forkswa.com/business-directory/business-category/lodging/rv-parks-campgrounds/'

BASE={'Park Type':'Private Campground','Archived':'false','Draft':'false','RV Access':'yes'}
ROWS={
 'quileute-oceanside-resort-rv-camping':{**BASE,'Park Type':'Tribal Campground','Name':'Quileute Oceanside Resort RV Camping','Nearest town':'La Push, WA','Number of RV campsites':'','Max RV length':'','Hookups':'3','Dump station on site':'','Amenities: Toilets':'Toilets','Amenities: Showers':'','Amenities: Drinking water':'true','Amenities: Fire pits':'true','Reservation window':'Reserve current ocean or river RV availability online','Reservation website':QUIL_BOOK,'Short Description':'Quileute Tribe-owned RV camping at First Beach with full hookups at oceanfront and river sites, picnic tables, fire rings, and direct online booking.','Long description':'Quileute Oceanside Resort offers full-service RV camping on First Beach in La Push. The Quileute Tribe owns and operates the resort. Both ocean and river RV site types include electric, water, and sewer hookups, a picnic table, and a fire ring. The operator intentionally does not provide television or Wi-Fi. The current public pages do not publish a campground-wide RV count or maximum rig length, so confirm the assigned site before towing.','Amenities summary':'Electric, water, and sewer at ocean and river RV sites, plus picnic tables and fire rings; no television or Wi-Fi.','Site Recommendations':'Choose an ocean or river site in the booking system, then confirm the assigned pad for your total rig length. Respect the Quileute Tribe photo and video policy while visiting.','Access note':'Use the named resort entrance at 330 Ocean Drive. RV inventory is split between ocean and river site types inside the resort.','Access source':QUIL,'Things to do for families':'Walk First Beach\nExplore Second and Third Beach trailheads\nWatch the sunset from camp\nVisit Rialto Beach\nExplore Forks\nLearn about Quileute culture respectfully','Things to do for families summary':'A full-hookup base directly on First Beach for coastal walks, sunsets, and west-side Olympic National Park trips.','Nearby nature & parks':'First Beach fronts the resort. Second Beach, Third Beach, Rialto Beach, and the Quillayute River are nearby, with Forks about 15 minutes east.','Hiking':'true','Fishing':'true','Swimming':'false','Kayaking/Paddling':'true','Beach & Tide Pools':'true','Boating':'true','Playground':'false','Nearby campgrounds':'three-rivers-resort-rv-camping;mora-campground;forks-101-rv-park;bogachiel-state-park'},
 'hobuck-beach-resort-rv-camping':{**BASE,'Park Type':'Tribal Campground','Name':'Hobuck Beach Resort RV Camping','Nearest town':'Neah Bay, WA','Number of RV campsites':'10','Max RV length':'','Hookups':'3','Dump station on site':'','Amenities: Toilets':'Toilets','Amenities: Showers':'true','Amenities: Drinking water':'true','Amenities: Fire pits':'false','Reservation window':'Ten full-hookup RV sites are first-come; call the office for current instructions','Reservation website':HOBUCK,'Short Description':'Makah Tribe-owned oceanfront resort with 10 first-come full-hookup pull-through RV sites, 30-amp service, showers, and beach access.','Long description':'Hobuck Beach Resort is a Makah Tribe enterprise on the Pacific coast near Neah Bay. The south side has 10 first-come RV sites with 30-amp electric, water, sewer, picnic tables, pull-through access, and bathhouse showers. The operator says the sites can accept long vehicles but does not publish a numeric maximum. A Makah Recreation Use Permit is required for each vehicle, and alcohol and marijuana are prohibited on the reservation.','Amenities summary':'Ten pull-through RV sites with 30-amp electric, water, sewer, picnic tables, and access to the bathhouse and free showers.','Site Recommendations':'The 10 hookup sites cannot be held for a later arrival. Call before the long drive, buy the required Makah Recreation Use Permit, and confirm fit if your rig is unusually long.','Access note':'The hookup RV area is at the south end of Hobuck Beach Resort. Check in at the office before entering the resort.','Access source':HOBUCK,'Things to do for families':'Walk Hobuck Beach\nHike Cape Flattery\nVisit the Makah Museum\nExplore Shi Shi Beach access\nWatch surfers and seabirds\nPhotograph Pacific sunsets','Things to do for families summary':'A rare full-hookup Pacific beach base for Cape Flattery, Makah cultural sites, and the outer coast.','Nearby nature & parks':'Hobuck Beach is steps from the RV area. Cape Flattery, Shi Shi Beach, the Makah Museum, and Neah Bay are the main nearby destinations.','Hiking':'true','Fishing':'true','Swimming':'false','Kayaking/Paddling':'true','Beach & Tide Pools':'true','Boating':'true','Playground':'false','Nearby campgrounds':'cape-resort-rv-park;ozette-campground;masons-resort-sekiu;anglers-hideaway-rv-park'},
 'cape-resort-rv-park':{**BASE,'Park Type':'Tribal Campground','Name':'Cape Resort RV Park','Nearest town':'Neah Bay, WA','Number of RV campsites':'39','Max RV length':'','Hookups':'3','Dump station on site':'','Amenities: Toilets':'Flush toilets','Amenities: Showers':'true','Amenities: Drinking water':'true','Amenities: Fire pits':'true','Reservation window':'Campsites are first-come; call the resort for current RV instructions','Reservation website':CAPE,'Short Description':'Makah Tribe enterprise in downtown Neah Bay with 39 full-hookup RV sites, some pull-throughs, showers, laundry, propane, and marina access.','Long description':'Cape Resort operates 39 RV sites in downtown Neah Bay on the Makah Reservation. The operator lists 30-amp electric, water, and sewer at RV sites, with some pull-through and sheltered choices and capacity for RVs over 31 feet. No campground-wide maximum is published, so the directory leaves the maximum blank and asks guests to confirm their assigned site. Restrooms, showers, laundry, propane, boat-trailer parking, and adjacent shops make this a practical service base. A Makah Recreation Use Permit is required.','Amenities summary':'30-amp electric, water, sewer, restrooms, showers, laundry, propane, garbage, and designated boat-trailer parking.','Site Recommendations':'The operator says some sites accept RVs over 31 feet but gives no universal maximum. Call with total rig length before making the drive; campsite instructions on the current page are internally inconsistent, so confirm availability by phone.','Access note':'Use the resort entrance at 1510 Bay View Avenue in downtown Neah Bay, near the marina and general store.','Access source':CAPE,'Things to do for families':'Visit the Makah Museum\nWalk Neah Bay shoreline\nHike Cape Flattery\nExplore Hobuck Beach\nWatch boats at the marina\nVisit Shi Shi Beach access','Things to do for families summary':'A service-rich downtown Neah Bay base for Makah cultural sites, Cape Flattery, the marina, and Pacific beaches.','Nearby nature & parks':'The resort is near Makah Marina and the bay shoreline, with Hobuck Beach and Cape Flattery a short drive west.','Hiking':'true','Fishing':'true','Swimming':'false','Kayaking/Paddling':'true','Beach & Tide Pools':'true','Boating':'true','Playground':'false','Nearby campgrounds':'hobuck-beach-resort-rv-camping;ozette-campground;masons-resort-sekiu;anglers-hideaway-rv-park'},
 'masons-resort-sekiu':{**BASE,'Name':"Mason's Resort Sekiu",'Nearest town':'Sekiu, WA','Number of RV campsites':'','Max RV length':'','Hookups':'3','Dump station on site':'','Amenities: Toilets':'Flush toilets','Amenities: Showers':'true','Amenities: Drinking water':'true','Amenities: Fire pits':'true','Reservation window':'RV and camping sites are first-come, first-served','Reservation website':MASON,'Short Description':'Working Sekiu fishing resort with full-hookup, water-and-electric, and dry RV choices plus showers, laundry, fuel, propane, store, and boat moorage.','Long description':"Mason's Resort, formerly Olson's Resort, is a waterfront fishing base in Sekiu. The operator currently offers full-hookup RV sites, water-and-electric sites, and dry camping on a first-come basis. Shower houses, restrooms, laundry, fuel, propane, a tackle store, a fish freezer, and boat moorage support fishing trips. The operator does not publish a current campground count or maximum RV length, so larger rigs should call before arrival.",'Amenities summary':'Full-hookup, water-and-electric, and dry camping choices with showers, restrooms, laundry, fuel, propane, tackle store, fish freezer, and moorage.','Site Recommendations':'Camping cannot be reserved. Call before departure for current space and describe your total rig length; moorage is also assigned on arrival.','Access note':'Use the operator address on Front Street in Sekiu. The campground and marina share the working resort property.','Access source':MASON,'Things to do for families':'Fish the Strait of Juan de Fuca\nWalk the Sekiu waterfront\nVisit Clallam Bay\nExplore nearby beaches\nTake a Cape Flattery day trip\nWatch boats from the marina','Things to do for families summary':'A practical fishing-focused waterfront base with moorage, supplies, and multiple utility levels.','Nearby nature & parks':'The campground faces the Strait of Juan de Fuca in Sekiu, between Clallam Bay and Neah Bay. Coastal beaches and Cape Flattery are reachable day trips.','Hiking':'true','Fishing':'true','Swimming':'false','Kayaking/Paddling':'true','Beach & Tide Pools':'true','Boating':'true','Playground':'false','Nearby campgrounds':'anglers-hideaway-rv-park;cape-resort-rv-park;hobuck-beach-resort-rv-camping;ozette-campground'},
 'anglers-hideaway-rv-park':{**BASE,'Name':'Anglers Hideaway RV Park','Nearest town':'Sekiu, WA','Number of RV campsites':'30','Max RV length':'38','Hookups':'3','Dump station on site':'false','Amenities: Toilets':'Flush toilets','Amenities: Showers':'true','Amenities: Drinking water':'true','Amenities: Fire pits':'false','Reservation window':'Reserve full-hookup RV sites online; two-week cancellation deadline','Reservation website':ANGLERS_BOOK,'Short Description':'Reservable Sekiu park with 30 full-hookup back-in RV sites, 30-amp service, selected 50-amp sites, showers, laundry, and a 38-foot limit.','Long description':'Anglers Hideaway is a locally operated RV park above the Sekiu waterfront. The current operator site lists 30 full-hookup back-in RV sites and a 38-foot maximum, with standard 30-amp service and selected premium 50-amp sites. Each hookup site has sewer, so the park does not offer a separate dump station. Restrooms, showers, laundry, boat-trailer parking, and online reservations are available. Guests must bring their own outdoor table and above-ground fire pit.','Amenities summary':'Full hookups, mostly 30-amp service with selected 50-amp sites, restrooms, showers, laundry, garbage, and guest boat-trailer parking.','Site Recommendations':'Back-in sites accept rigs up to 38 feet. Bring an outdoor table and an above-ground fire pit if needed; no fish cleaning is allowed in the park.','Access note':'Use the named Waze destination at 12 Park Loop Drive. The park sits above Sekiu; follow the operator directions from SR 112 via Airport Road.','Access source':ANGLERS,'Things to do for families':'Fish from Sekiu-area waters\nBeachcomb along the Strait\nWalk the Sekiu waterfront\nVisit Clallam Bay\nExplore Shipwreck Point\nTake a Cape Flattery day trip','Things to do for families summary':'A reservable full-hookup base for Sekiu fishing trips and western Strait of Juan de Fuca beaches.','Nearby nature & parks':'Sekiu overlooks the Strait of Juan de Fuca near Clallam Bay. Shipwreck Point, local beaches, and Neah Bay are west along SR 112.','Hiking':'true','Fishing':'true','Swimming':'false','Kayaking/Paddling':'true','Beach & Tide Pools':'true','Boating':'true','Playground':'false','Nearby campgrounds':'masons-resort-sekiu;cape-resort-rv-park;hobuck-beach-resort-rv-camping;ozette-campground'},
 'three-rivers-resort-rv-camping':{**BASE,'Name':'Three Rivers Resort RV Camping','Nearest town':'Forks, WA','Number of RV campsites':'','Max RV length':'','Hookups':'3','Dump station on site':'','Amenities: Toilets':'Flush toilets','Amenities: Showers':'true','Amenities: Drinking water':'true','Amenities: Fire pits':'true','Reservation window':'Check current full- or partial-hookup RV availability online','Reservation website':'https://reservation.asiwebres.com/v5/RoomAvailability.aspx?Curr=1&id=529ee5c9745748ff8a95aa203141ebb9&lang=en','Short Description':'Private resort on La Push Road with full- and partial-hookup RV sites, online availability, showers, laundry, Wi-Fi, store, cafe, and circle-drive access.','Long description':'3 Rivers Resort sits on SR 110 between Forks and La Push. Current operator pages list both full-hookup RV sites with water, sewer, and electric and half-hookup sites with water and electric. Guests have access to picnic tables, Wi-Fi, hot showers, restrooms, laundry, boat parking, a store, and a cafe. The circle-drive layout supports simple arrivals, but the operator publishes neither a current RV-site count nor a numeric maximum, so confirm fit when booking.','Amenities summary':'Full- or partial-hookup RV sites with picnic tables, Wi-Fi, hot showers, restrooms, laundry, boat parking, store, and cafe.','Site Recommendations':'Choose full hookups when sewer matters. The operator says the circle drive fits most RVs but gives no maximum length, so confirm total rig dimensions before booking.','Access note':'Use the operator-published coordinates at 7764 La Push Road, about eight miles west of Forks.','Access source':'https://forkslodging.net/3-rivers-resort/directions/','Things to do for families':'Visit First, Second, and Rialto beaches\nExplore Forks\nFish nearby rivers\nHike Olympic National Park trails\nVisit the Quileute coast respectfully\nUse the on-site store and cafe','Things to do for families summary':'A hookup-equipped midpoint between Forks and La Push for river, rainforest, and Pacific beach trips.','Nearby nature & parks':'The resort sits near the Sol Duc, Bogachiel, and Quillayute river system, with La Push beaches west and Forks east.','Hiking':'true','Fishing':'true','Swimming':'false','Kayaking/Paddling':'true','Beach & Tide Pools':'true','Boating':'true','Playground':'false','Nearby campgrounds':'quileute-oceanside-resort-rv-camping;mora-campground;forks-101-rv-park;bogachiel-state-park'}
}

def duration(m):
 h,mm=divmod(m,60); return f'~{h} hr {mm} min from Seattle' if mm else f'~{h} hr from Seattle'
def src(url,publisher,note): return {'url':url,'publisher':publisher,'source_family':'clallam-private-review','evidence':note}

def main():
 reviews={r['slug']:r for r in json.loads(REVIEWS.read_text())['reviews']}
 with MASTER.open(newline='',encoding='utf-8-sig') as f: reader=csv.DictReader(f); fields=list(reader.fieldnames or []); rows=list(reader)
 by={r['Slug']:r for r in rows}
 for slug,c in ROWS.items():
  r=reviews[slug]; m=r['display_minutes']; row=by.get(slug,{k:'' for k in fields})
  row.update(c); row.update({'Slug':slug,'Data last updated':CHECKED,'Topographic background image':f'https://westcoastrvcamping.com/assets/images/topo/{slug}.jpg','Time from Seattle':duration(m),'Drive Time Band':'4plus','Drive Time Minutes':str(m),'Address':r['address'],'Maneuverability':'2','Site surface type':'Gravel','Generator policy':'','Cell coverage':'0','Google Maps Link':f"https://www.google.com/maps?q={r['latitude']:.7f},{r['longitude']:.7f}",'State Map':f'/assets/images/svg/{slug}.svg','Access checked':CHECKED,'Latitude':f"{r['latitude']:.7f}",'Longitude':f"{r['longitude']:.7f}",'Coordinates source':r['coordinate_source'],'Coordinates checked':CHECKED,'Coordinate precision':r['precision'],'Drive distance miles':str(r['distance_miles']),'Drive route minutes':str(r['observed_route_minutes']),'Drive time origin':'Seattle, Washington','Drive time source':f"https://www.google.com/maps/dir/?api=1&origin=Seattle%2C%20Washington&destination={r['latitude']:.7f},{r['longitude']:.7f}&travelmode=driving",'Drive time checked':CHECKED,'Drive time note':r['route_note']})
  if slug not in by: rows.append(row)
  by[slug]=row

 # Four existing private records had unsupported or contradictory copy.
 by['elwha-dam-rv-park'].update({'Data last updated':CHECKED,'Name':'Elwha Dam RV Park','Number of RV campsites':'','Reservation window':'Book current daily or weekly site types online; summer weekends generally require two nights','Short Description':'Wooded year-round RV park west of Port Angeles with full-hookup and water-and-electric sites, 70-by-30-foot premium pull-throughs, showers, laundry, and online booking.','Long description':'Elwha RV Park & Campground is a wooded private park west of Port Angeles near the former Elwha Dam site. The operator lists full-hookup and water-and-electric site types, plus 70-by-30-foot premium pull-throughs that can accept a 45-foot fifth wheel with its tow vehicle or a 40-foot motorhome with a 20-foot utility trailer. Restrooms, showers, laundry, Wi-Fi, a clubhouse, fire rings, and walking trails are available. The operator does not publish a current RV-site count, so this record no longer repeats the older conflicting totals.','Number of RV campsites':'','Site Recommendations':'Premium pull-throughs measure 70 by 30 feet. Confirm the site type for your utility needs; Wi-Fi is strongest around the office, bathhouse, and clubhouse.','Access note':'Follow the operator directions from SR 112 to Lower Dam Road; the entrance point is published by the operator.','Access source':'https://elwharvpark.com/contact-us/','Access checked':CHECKED,'Latitude':'48.0978590','Longitude':'-123.5528090','Google Maps Link':'https://www.google.com/maps?q=48.0978590,-123.5528090','Coordinates source':'Operator-published GPS coordinates','Coordinates checked':CHECKED,'Coordinate precision':'operator-published entrance point','Nearby campgrounds':'crescent-beach-rv-park;salt-creek-recreation-area;heart-o-the-hills-campground;log-cabin-resort-rv-campground'})
 by['forks-101-rv-park'].update({'Data last updated':CHECKED,'Name':'Forks 101 RV Park','Max RV length':'','Reservation window':'Reserve current daily or weekly availability online; winter and summer rates vary','Short Description':'Thirty-three-site full-hookup RV park in Forks with 20/30/50-amp service, showers, laundry, fire pits, picnic tables, and online reservations.','Long description':'Forks RV Park is a private campground inside the Forks city limits. The operator confirms 33 full-hookup sites with 20-, 30-, and 50-amp service, restrooms, hot showers, laundry, fire pits, picnic tables, and Wi-Fi at selected sites. Grocery shopping and restaurants are across US 101. Current winter pricing shows the park operates beyond the older May-through-October description. The operator calls the sites big-rig friendly but does not publish a numeric maximum, so this record no longer claims a 75-foot limit.','Site Recommendations':'The park describes landscaped sites for both large and small rigs but publishes no campground-wide maximum. Enter your exact dimensions when reserving.','Access note':'The entrance is at the operator-published 901 South Forks Avenue address, across US 101 from Forks Outfitters.','Access source':'https://www.forksrvpark.com/','Access checked':CHECKED,'Nearby campgrounds':'bogachiel-state-park;three-rivers-resort-rv-camping;mora-campground;quileute-oceanside-resort-rv-camping'})
 by['crescent-beach-rv-park'].update({'Data last updated':CHECKED,'Number of RV campsites':'','Max RV length':'','Reservation window':'Reservations are required for RV sites; book online, by phone, or in person','Short Description':'Seafront private campground west of Port Angeles with full- and partial-hookup RV sites, showers, laundry, private beach access, picnic tables, and fire pits.','Long description':'Crescent Beach & RV Park sits on the Strait of Juan de Fuca west of Port Angeles. Current operator pages list full-hookup sites with water, electric, and sewer and partial-hookup sites with water and electric. There is no on-site dump station for partial-hookup guests. Picnic tables, fire pits, restrooms, hot showers, laundry, a small store, and access to the operator\'s half-mile private beach are available. The operator does not publish a current RV count or campground-wide maximum, so both older figures have been removed.','Site Recommendations':'Choose a full-hookup site if you need sewer; partial sites have no sewer and the park has no dump station. Confirm the assigned pad against your exact RV length.','Access note':'Use the named campground entrance at the operator-published Crescent Beach Road address.','Access source':'https://www.crescentbeachrv.com/rvpark','Access checked':CHECKED,'Nearby campgrounds':'salt-creek-recreation-area;elwha-dam-rv-park;lyre-river-campground;dungeness-recreation-area'})
 by['gilgal-oasis-rv-park'].update({'Data last updated':CHECKED,'Max RV length':'','Dump station on site':'','Reservation window':'Check current nightly or extended-stay availability with the park','Short Description':'Year-round Sequim RV park with 28 paved full-hookup sites, 20/30/50-amp service, showers, laundry, clubhouse, Wi-Fi, and downtown access.','Long description':'Gilgal Oasis RV Park has 28 paved back-in and pull-through sites in Sequim. Every site has 20-, 30-, and 50-amp electric, city water, and sewer. The park also provides showers, accessible restrooms, laundry, a clubhouse, Wi-Fi, picnic tables, and a fenced dog area. The operator describes downtown as walkable and places major stores within a short drive; the older copy incorrectly said Costco and other services were all within one mile. The operator does not publish a campground-wide maximum RV length.','Site Recommendations':'All 28 sites have full hookups. Ask for a pull-through if needed and confirm total rig dimensions because the operator publishes no park-wide maximum length.','Access note':'Use the operator address at 400 South Brown Road in Sequim. The park is near downtown and the Olympic Discovery Trail.','Access source':'https://www.gilgaloasisrvpark.com/amenities/','Access checked':CHECKED,'Nearby campgrounds':'sequim-bay-state-park;dungeness-recreation-area;heart-o-the-hills-campground;elwha-dam-rv-park'})
 with MASTER.open('w',newline='',encoding='utf-8') as f: w=csv.DictWriter(f,fieldnames=fields,lineterminator='\n'); w.writeheader(); w.writerows(rows)

 coverage=json.loads(COVERAGE.read_text()); coverage['updated_on']=CHECKED
 section=next(s for s in coverage['sections'] if s['id']=='clallam-private-tribal')
 section.update({'status':'complete','inventory_sources':[MAKAH,FORKS,QUIL,HOBUCK,CAPE,MASON,ANGLERS,THREE],'candidates':[
  *[{'name':ROWS[s]['Name'],'slug':s,'decision':'included_new','reason':'Current operator pages support transient RV camping and the published utility details.'} for s in ROWS],
  *[{'name':by[s]['Name'],'slug':s,'decision':'included_existing','reason':'Current operator pages support transient RV operation; unsupported copy was corrected.'} for s in ('elwha-dam-rv-park','forks-101-rv-park','crescent-beach-rv-park','gilgal-oasis-rv-park')],
  {'name':'Hide-Away RV Park','decision':'deferred','reason':'The Makah visitor inventory confirms current operation, but the former operator domain now redirects to unrelated gambling content and no direct reservation source is available.'},
  {'name':'The Village RV','decision':'deferred','reason':'The Makah visitor inventory lists 26 full-hookup sites, but no stable operator or reservation page was found.'},
  {'name':'Lost Resort at Lake Ozette','decision':'deferred','reason':'Current local inventory supports camping, but present RV count, rig limit, utilities, and stable operator details could not all be verified.'},
  {'name':'Van Riper’s Resort','decision':'deferred','reason':'Local inventories identify RV camping, but no current stable operator page was available for a source-backed record.'},
  {'name':'Riverview RV Park','decision':'deferred','reason':'A current Forks inventory names the property, but the available detailed source is older and the current reservation channel was not verified.'},
  {'name':'Cycle Camp','decision':'excluded','reason':'The operator targets bicycle and motorcycle tent campers rather than RV travelers.'},
  {'name':'Camp David Jr.','decision':'excluded','reason':'County facility is group-use only and not an individual transient RV campground.'}
 ]})
 COVERAGE.write_text(json.dumps(coverage,indent=2)+'\n')

 evidence=json.loads(EVIDENCE.read_text()); affected=set(ROWS)|{'elwha-dam-rv-park','forks-101-rv-park','crescent-beach-rv-park','gilgal-oasis-rv-park'}
 evidence['observations']=[o for o in evidence['observations'] if not (o.get('slug') in affected and o.get('source_family')=='clallam-private-review')]
 sources={
  'quileute-oceanside-resort-rv-camping':[src(QUIL,'Quileute Oceanside Resort','Operator confirms ocean and river RV sites with full hookups.'),src('https://quileuteoceanside.com/','Quileute Oceanside Resort','Operator confirms tribal ownership, location, and current booking.')],
  'hobuck-beach-resort-rv-camping':[src(HOBUCK,'Hobuck Beach Resort / Makah Tribe','Operator confirms 10 first-come RV sites, full hookups, pull-through access, and showers.')],
  'cape-resort-rv-park':[src(CAPE,'Cape Resort / Makah Tribe','Operator confirms 39 RV sites, utilities, facilities, and RV capacity over 31 feet.')],
  'masons-resort-sekiu':[src(MASON,"Mason's Resort",'Operator confirms current first-come full-hookup, partial-hookup, and dry RV camping.')],
  'anglers-hideaway-rv-park':[src(ANGLERS,'Anglers Hideaway','Operator confirms 30 full-hookup sites, 38-foot maximum, facilities, and reservations.')],
  'three-rivers-resort-rv-camping':[src(THREE,'3 Rivers Resort','Operator confirms current full- and partial-hookup RV sites, facilities, and booking.')]
 }
 for slug,c in ROWS.items():
  for field,value in {'operating_status':'current transient RV camping','rv_access':True,'reservation_method':c['Reservation window'],'max_rv_length':int(c['Max RV length']) if c['Max RV length'] else None,'hookups':int(c['Hookups'])}.items():
   if value is None:
    continue
   evidence['observations'].append({'slug':slug,'field':field,'status':'supported','checked_on':CHECKED,'summary':f'Current operator review supports {field.replace("_"," ")}.','proposed_value':value,'source_family':'clallam-private-review','sources':sources[slug]})
 corrections={'elwha-dam-rv-park':['conflicting site totals removed','operator GPS point adopted','unsupported river-fishing claim removed'],'forks-101-rv-park':['unsupported 75-foot limit removed','incorrect seasonal closure removed'],'crescent-beach-rv-park':['unsupported site count removed','unsupported park-wide length removed'],'gilgal-oasis-rv-park':['incorrect within-one-mile shopping claim corrected','unsupported park-wide length removed']}
 existing_sources={'elwha-dam-rv-park':'https://elwharvpark.com/faq/','forks-101-rv-park':'https://www.forksrvpark.com/','crescent-beach-rv-park':'https://www.crescentbeachrv.com/rvpark','gilgal-oasis-rv-park':'https://www.gilgaloasisrvpark.com/amenities/'}
 for slug,items in corrections.items(): evidence['observations'].append({'slug':slug,'field':'content_scrub','status':'corrected_locally','checked_on':CHECKED,'summary':'; '.join(items)+'.','proposed_value':items,'source_family':'clallam-private-review','sources':[src(existing_sources[slug],by[slug]['Name'],'Current operator page supports the corrected record.')]})
 EVIDENCE.write_text(json.dumps(evidence,indent=2)+'\n')
 print(f'Completed Clallam private/tribal phase: added {len(ROWS)} campgrounds and corrected 9 grouped factual issues across 4 existing records. Dataset now has {len(rows)} records.')

if __name__=='__main__': main()
