#!/usr/bin/env python3
"""Publish the reviewed Snohomish County-operated RV camping layer."""
import csv, json
from pathlib import Path

HERE=Path(__file__).resolve().parent
MASTER=HERE/'data/campgrounds.csv'; EVIDENCE=HERE/'verification-evidence.json'; COVERAGE=HERE/'coverage-inventory.json'
REVIEWS=HERE/'snohomish-county-location-reviews.json'; CHECKED='2026-09-12'
COUNTY='https://www.snohomishcountywa.gov/1082/Campgrounds'
BOOK='https://reservations.snocoparks.org/reservation/camping/?parent_idno=112'
RULES='https://www.snohomishcountywa.gov/1263/Rules-Policies-Regulations'
FLOW='https://www.snohomishcountywa.gov/Facilities/Facility/Details/Flowing-Lake-Park-Campground-at-Leckies--31'
FLOW_MAP='https://snohomishcountywa.gov/DocumentCenter/View/107346/Flowing-Lake-Park--Campground-Map-2025'
KAYAK='https://snohomishcountywa.gov/facilities/facility/details/kayakpointregionalcountypark-51'
WENBERG='https://www.snohomishcountywa.gov/facilities/facility/details/Wenberg-County-Park-62'
RIVER='https://www.snohomishcountywa.gov/Facilities/Facility/Details/River-Meadows-Park-46'
SQUIRE='https://snohomishcountywa.gov/facilities/facility/details/Squire-Creek-Park-Campground-54'
WHITE='https://www.snohomishcountywa.gov/facilities/facility/details/Whitehorse-Campground-190'
FAIR='https://evergreenfair.org/203/Plan-Your-Stay'

BASE={'Park Type':'County Campground','Archived':'false','Draft':'false','RV Access':'yes','Generator policy':'1','Cell coverage':'0'}
NEW={
 'river-meadows-county-park':{**BASE,'Name':'River Meadows County Park','Nearest town':'Arlington, WA','Number of RV campsites':'10','Max RV length':'','Maneuverability':'2','Site surface type':'Gravel','Hookups':'0','Dump station on site':'false','Amenities: Toilets':'Flush toilets','Amenities: Showers':'false','Amenities: Drinking water':'true','Amenities: Fire pits':'true','Reservation window':'Reserve at least 3 days before arrival; weekend reservations require Friday and Saturday','Reservation website':BOOK,'Short Description':'Ten nonutility drive-up RV and tent sites beside the Stillaguamish River, with running water nearby and seasonal restrooms.','Long description':'River Meadows County Park protects 150 acres and about a mile of Stillaguamish River frontage near Arlington. Its campground has 10 drive-up sites identified for RV or tent use, plus four separate hike-in sites and six yurts. Drive-up sites have fire rings and running water nearby but no utility hookups. Campground restrooms are seasonal, and the yurt building showers are reserved for yurt guests. The county publishes no campground-wide RV length limit, so confirm the pad description before reserving.','Amenities summary':'Nonutility drive-up sites with nearby water, fire rings, seasonal campground restrooms, and winter portable toilets; campsite guests do not have shower access.','Site Recommendations':'Choose from the 10 drive-up RV or tent sites. Check the reservation description for the individual pad and confirm fit before towing.','Access note':'Use the named county park entrance on Jordan Road. The drive-up campground is separate from the four hike-in sites.','Access source':RIVER,'Things to do for families':'Walk the riverbank\nFish the Stillaguamish River\nPicnic in the park\nExplore meadow trails\nWatch wildlife','Things to do for families summary':'A quiet nonutility river campground with meadow walks, fishing access, and room to explore.','Nearby nature & parks':'The park follows the Stillaguamish River near Arlington, with broad meadows, forest edges, and access to the Mountain Loop region.','Hiking':'true','Fishing':'true','Swimming':'false','Kayaking/Paddling':'false','Beach & Tide Pools':'false','Boating':'false','Playground':'false','Nearby campgrounds':'squire-creek-park-campground;whitehorse-campground;flowing-lake-county-park;gold-basin-campground'},
 'squire-creek-park-campground':{**BASE,'Name':'Squire Creek Park Campground','Nearest town':'Darrington, WA','Number of RV campsites':'','Max RV length':'','Maneuverability':'2','Site surface type':'Gravel','Hookups':'0','Dump station on site':'false','Amenities: Toilets':'Flush toilets','Amenities: Showers':'false','Amenities: Drinking water':'true','Amenities: Fire pits':'true','Reservation window':'Reserve at least 3 days before arrival; weekend reservations require Friday and Saturday','Reservation website':BOOK,'Short Description':'Mossy forest campground near Darrington with 33 nonutility sites, many RV-capable, and site-specific pad lengths.','Long description':'Squire Creek Park Campground has 33 nonutility campsites in a mossy forest west of Darrington. The county says many sites have room for RVs, and the campground map identifies back-in and pull-through layouts, but it does not say all 33 are RV-capable or publish one park-wide length limit. Water spigots and flush restrooms operate seasonally; portable toilets replace the restrooms outside the main season. There are no showers or dump station. Use each reservation listing to verify pad length and vehicle fit.','Amenities summary':'Nonutility sites with fire rings, seasonal water spigots and flush restrooms, and portable toilets outside the main season; no showers or dump station.','Site Recommendations':'Use the reservation system pad dimensions to choose among back-in and pull-through sites. Confirm total vehicle and trailer length before arrival.','Access note':'Use the named Squire Creek Park campground destination from SR 530. The park is west of Darrington.','Access source':SQUIRE,'Things to do for families':'Walk forest paths\nExplore the Mountain Loop area\nVisit Darrington\nReach Sauk River access nearby\nWatch forest wildlife','Things to do for families summary':'A simple forest base for Darrington, the Sauk River corridor, and Mountain Loop day trips.','Nearby nature & parks':'The campground lies below Whitehorse Mountain near Darrington and the Mount Baker-Snoqualmie National Forest. Sauk River access is available at nearby Backman Park.','Hiking':'true','Fishing':'true','Swimming':'false','Kayaking/Paddling':'false','Beach & Tide Pools':'false','Boating':'false','Playground':'false','Nearby campgrounds':'whitehorse-campground;river-meadows-county-park;gold-basin-campground;bedal-campground'},
 'whitehorse-campground':{**BASE,'Name':'Whitehorse Campground','Nearest town':'Darrington, WA','Number of RV campsites':'15','Max RV length':'','Maneuverability':'2','Site surface type':'Gravel','Hookups':'3','Dump station on site':'true','Amenities: Toilets':'Flush toilets','Amenities: Showers':'true','Amenities: Drinking water':'true','Amenities: Fire pits':'true','Reservation window':'Reserve at least 3 days before arrival; campground closes during winterization','Reservation website':BOOK,'Short Description':'Darrington campground with 15 full-utility RV or equestrian sites, an on-site dump station, accessible showers, and mountain access.','Long description':'Whitehorse Campground has 30 sites near Darrington. Sites 1 through 13 form the full-utility RV loop with water, 50-amp electric, and sewer; sites 14 and 15 are full-utility equestrian sites. Sites 16 through 18 are nonutility equestrian sites, and sites 19 through 30 are tent-only with no RVs or trailers allowed. The campground has an on-site dump station, restrooms, and accessible showers. The county does not publish one maximum RV length, so check the reserved site dimensions. The campground closes during its winterization period.','Amenities summary':'Fifteen full-utility RV or equestrian sites, an on-site dump station, flush restrooms, accessible showers, water, and fire rings.','Site Recommendations':'RV sites 1 through 13 and equestrian sites 14 and 15 have full utilities. Check the selected site dimensions; sites 19 through 30 do not accept RVs or trailers.','Access note':'Use the named campground entrance on North Mountain Road. Current county information says there is no direct campground connection to the Whitehorse Trail.','Access source':WHITE,'Things to do for families':'Explore Darrington\nHike nearby national forest trails\nFish the Sauk River corridor\nVisit Mountain Loop viewpoints\nUse the equestrian facilities','Things to do for families summary':'A full-utility base near Darrington for mountain, river, and national forest trips.','Nearby nature & parks':'Whitehorse Mountain rises above the Darrington area, with the Sauk River and Mount Baker-Snoqualmie National Forest nearby.','Hiking':'true','Fishing':'true','Swimming':'false','Kayaking/Paddling':'false','Beach & Tide Pools':'false','Boating':'false','Playground':'false','Nearby campgrounds':'squire-creek-park-campground;river-meadows-county-park;bedal-campground;gold-basin-campground'},
 'evergreen-state-fairgrounds-rv-2':{**BASE,'Name':'Evergreen State Fairgrounds RV-2','Nearest town':'Monroe, WA','Number of RV campsites':'117','Max RV length':'42','Maneuverability':'3','Site surface type':'Gravel','Hookups':'2','Dump station on site':'true','Amenities: Toilets':'Flush toilets','Amenities: Showers':'true','Amenities: Drinking water':'true','Amenities: Fire pits':'false','Reservation window':'Seasonal public RV stays April 1 through October 31, excluding fair dates; maximum 7 nights','Reservation website':BOOK,'Short Description':'Seasonal Monroe fairgrounds RV lot with 117 water-and-electric sites, 24 pull-throughs, a dump station, and a 42-foot limit.','Long description':'Evergreen State Fairgrounds RV-2 is the fairgrounds area open to general public RV stays, typically April 1 through October 31 outside annual fair dates. The current operator page lists 117 water-and-electric sites with 30/20-amp service, including 24 pull-throughs, a dump station, restrooms, and showers. There are no sewer hookups at individual sites, picnic tables, or traditional campfires. The published maximum RV length is 42 feet and the maximum stay is seven nights. RV-1 is reserved for event use and is not part of this listing.','Amenities summary':'Water and 30/20-amp electric at 117 sites, 24 pull-throughs, dump station, restrooms, and showers; no individual sewer, picnic tables, or campfires.','Site Recommendations':'Use RV-2 for general public stays. Confirm that your dates do not overlap the annual fair or another closure and keep total RV length within 42 feet.','Access note':'Navigate to the named RV-2 area at the Evergreen State Fairgrounds. RV-1 is event-only.','Access source':FAIR,'Things to do for families':'Visit Monroe\nAttend fairgrounds events\nExplore the Skykomish Valley\nTake day trips toward Stevens Pass\nUse nearby town services','Things to do for families summary':'A practical utility-equipped staging stop in Monroe with quick access to town and the US 2 corridor.','Nearby nature & parks':'The fairgrounds sit in Monroe near the Skykomish River valley and the western approach to Stevens Pass.','Hiking':'false','Fishing':'false','Swimming':'false','Kayaking/Paddling':'false','Beach & Tide Pools':'false','Boating':'false','Playground':'false','Nearby campgrounds':'flowing-lake-county-park;river-meadows-county-park;turlo-campground;verlot-campground'}
}

def duration(minutes):
 h,m=divmod(minutes,60)
 return f'~{h} hr {m} min from Seattle' if m else f'~{h} hr from Seattle'
def source(url,note): return {'url':url,'publisher':'Snohomish County','source_family':'snohomish-county-review','evidence':note}

def main():
 reviews={r['slug']:r for r in json.loads(REVIEWS.read_text())['reviews']}
 with MASTER.open(newline='',encoding='utf-8-sig') as f: reader=csv.DictReader(f); fields=list(reader.fieldnames or []); rows=list(reader)
 by={r['Slug']:r for r in rows}
 for slug,data in NEW.items():
  rv=reviews[slug]; row=by.get(slug,{k:'' for k in fields}); row.update(data)
  row.update({'Slug':slug,'Data last updated':CHECKED,'Topographic background image':f'https://westcoastrvcamping.com/assets/images/topo/{slug}.jpg','Time from Seattle':duration(rv['display_minutes']),'Drive Time Band':'under-1hr' if rv['display_minutes']<60 else '1-2hrs' if rv['display_minutes']<120 else '2-3hrs','Drive Time Minutes':str(rv['display_minutes']),'Address':rv['address'],'Google Maps Link':f"https://www.google.com/maps?q={rv['latitude']:.7f},{rv['longitude']:.7f}",'State Map':f'/assets/images/svg/{slug}.svg','Access checked':CHECKED,'Latitude':f"{rv['latitude']:.7f}",'Longitude':f"{rv['longitude']:.7f}",'Coordinates source':rv['coordinate_source'],'Coordinates checked':CHECKED,'Coordinate precision':rv['precision'],'Drive distance miles':str(rv['distance_miles']),'Drive route minutes':str(rv['observed_route_minutes']),'Drive time origin':'Seattle, Washington','Drive time source':f"https://www.google.com/maps/dir/?api=1&origin=Seattle%2C%20Washington&destination={rv['latitude']:.7f},{rv['longitude']:.7f}&travelmode=driving",'Drive time checked':CHECKED,'Drive time note':rv['route_note']})
  if slug not in by: rows.append(row)
  by[slug]=row

 updates={
  'flowing-lake-county-park':{'Number of RV campsites':'39','Max RV length':'','Hookups':'2','Dump station on site':'false','Reservation window':'Reserve at least 3 days before arrival; weekend reservations require Friday and Saturday','Reservation website':BOOK,'Short Description':'Forested lake campground with 39 utility RV sites, a swim beach, playground, showers, and year-round access with reduced winter services.','Long description':'Flowing Lake Park surrounds a 132.5-acre lake. Its current campground map labels 39 numbered utility sites, seven drive-up nonutility sites, and four hike-in sites, while the facility page states 48 campsites overall. Because those totals conflict, this RV listing uses only the 39 clearly mapped utility sites rather than treating every campsite as RV-capable. Utility amperage varies by site. The county specifically prohibits fifth-wheels longer than 35 feet because of internal road limits, but does not publish one universal limit for every RV type. There is no dump station; the county directs guests to Evergreen State Fairgrounds. Winterization closes nonutility sites and shuts off campground water, while the restroom remains open.','Things to do for families':'Swimming\nFishing\nKayaking or paddling\nPlayground\nPicnicking\nWalking park trails','Things to do for families summary':'A forested county lake campground with a swim beach, fishing, paddling, and playground close to Snohomish.','Nearby nature & parks':'Flowing Lake Park surrounds a forested lowland lake east of Snohomish at the edge of the Cascade foothills.','Site Recommendations':'Check the reservation map for the utility type and pad dimensions. Fifth-wheels longer than 35 feet are prohibited; the county publishes no universal limit for other RV types.','Access note':'Use the named Flowing Lake Park campground entrance at the county-published address.','Access source':FLOW},
  'kayak-point-regional-park':{'Number of RV campsites':'30','Max RV length':'','Hookups':'2','Dump station on site':'false','Reservation window':'Reserve at least 3 days before arrival; weekend reservations require Friday and Saturday','Reservation website':BOOK,'Short Description':'Thirty-site water-and-electric campground above Puget Sound with a 300-foot fishing pier, beach access, showers, and site-specific pad sizes.','Long description':'Kayak Point Regional Park has 30 partial-utility RV sites with water and 50/30/20-amp electric service, plus 10 yurts. The shoreline extends about 3,300 feet and includes a 300-foot fishing pier. The county does not publish one campground-wide RV length limit; verify the selected pad before towing. There is no dump station. During the current improvement project, the campground and northern park area remain open, while the south day-use area and playground are closed through fall 2026. Check the county project update before traveling.','Things to do for families':'Walk the Puget Sound shoreline\nFish from the 300-foot pier\nKayak or paddle\nUse the boat launch\nExplore the beach\nStay in a yurt','Things to do for families summary':'Puget Sound shoreline camping with a 300-foot fishing pier, beach access, paddling, and boating.','Nearby nature & parks':'The park occupies forested Puget Sound shoreline on Port Susan, west of Stanwood.','Site Recommendations':'All 30 RV sites have water and 50/30/20-amp electric service. Check the current construction notice and the reservation listing for exact pad size.','Access note':'Use the named campground entrance on Marine Drive. The campground remains open during the current south day-use construction project.','Access source':KAYAK},
  'wenberg-county-park':{'Number of RV campsites':'70','Max RV length':'','Hookups':'3','Dump station on site':'true','Reservation window':'Reserve at least 3 days before arrival; winter camping is drop-in with reduced utilities','Reservation website':BOOK,'Short Description':'Seventy-site Lake Goodwin campground with full-, partial-, and nonutility loops, a swim beach, boat launch, showers, and dump station.','Long description':'Wenberg County Park has a 70-site campground on the east shore of Lake Goodwin. Loop 1 mixes full- and partial-utility sites and remains available year-round with reduced winter utilities. Loop 2 mixes partial-utility and nonutility sites and closes seasonally; Loop 3 is mostly nonutility and best suited to tents. The park also has 1,140 feet of shoreline, an enclosed swim area, a two-lane concrete boat launch, restrooms, showers, and a dump station. The county does not publish one campground-wide RV length limit, so use the reservation listing for pad fit.','Things to do for families':'Swim at the enclosed beach\nLaunch a boat\nFish Lake Goodwin\nKayak or paddle\nUse the playground\nPicnic by the lake','Things to do for families summary':'Lake Goodwin camping with utility choices, swimming, boating, fishing, showers, and a playground.','Nearby nature & parks':'Wenberg County Park occupies the east shore of Lake Goodwin west of Stanwood.','Site Recommendations':'Loops have different utility levels and seasonal dates. Loop 3 is mostly nonutility and best suited to tents; confirm the selected pad before towing.','Access note':'Use the named Wenberg County Park campground entrance at the county-published address.','Access source':WENBERG}
 }
 for slug,data in updates.items():
  by[slug].update(data); by[slug]['Data last updated']=CHECKED; by[slug]['Draft']='false'; by[slug]['RV Access']='yes'; by[slug]['Cell coverage']='0'
  rv=reviews[slug]; by[slug].update({'Time from Seattle':duration(rv['display_minutes']),'Drive Time Band':'1-2hrs','Drive Time Minutes':str(rv['display_minutes']),'Address':rv['address'],'Google Maps Link':f"https://www.google.com/maps?q={rv['latitude']:.7f},{rv['longitude']:.7f}",'Access checked':CHECKED,'Latitude':f"{rv['latitude']:.7f}",'Longitude':f"{rv['longitude']:.7f}",'Coordinates source':rv['coordinate_source'],'Coordinates checked':CHECKED,'Coordinate precision':rv['precision'],'Drive distance miles':str(rv['distance_miles']),'Drive route minutes':str(rv['observed_route_minutes']),'Drive time origin':'Seattle, Washington','Drive time source':f"https://www.google.com/maps/dir/?api=1&origin=Seattle%2C%20Washington&destination={rv['latitude']:.7f},{rv['longitude']:.7f}&travelmode=driving",'Drive time checked':CHECKED,'Drive time note':rv['route_note']})
 with MASTER.open('w',newline='',encoding='utf-8') as f: w=csv.DictWriter(f,fieldnames=fields,lineterminator='\n'); w.writeheader(); w.writerows(rows)

 coverage=json.loads(COVERAGE.read_text()); coverage['updated_on']=CHECKED
 coverage['sections']=[s for s in coverage['sections'] if s.get('id')!='snohomish-county']
 coverage['sections'].append({'id':'snohomish-county','name':'Snohomish County-operated campgrounds','status':'complete','inventory_sources':[COUNTY,FLOW,FLOW_MAP,KAYAK,WENBERG,RIVER,SQUIRE,WHITE,FAIR],'candidates':[
  *[{'name':by[s]['Name'],'slug':s,'decision':'included_existing','reason':'Current county pages support RV camping; stale or unsupported facts were corrected.'} for s in updates],
  *[{'name':NEW[s]['Name'],'slug':s,'decision':'included_new','reason':'Current county pages and maps explicitly support transient RV camping.'} for s in NEW],
  {'name':'Lake Roesiger Group Camp','decision':'excluded','reason':'The county inventory identifies this as group camping rather than individual transient RV sites.'},
  {'name':'Evergreen State Fairgrounds RV-1','decision':'excluded','reason':'RV-1 is available only for fairgrounds events; general public RV stays use RV-2.'}
 ]})
 COVERAGE.write_text(json.dumps(coverage,indent=2)+'\n')

 evidence=json.loads(EVIDENCE.read_text()); affected=set(NEW)|set(updates)
 evidence['observations']=[o for o in evidence['observations'] if not (o.get('slug') in affected and o.get('source_family')=='snohomish-county-review')]
 urls={**{s:NEW[s]['Access source'] for s in NEW},**{s:updates[s]['Access source'] for s in updates}}
 for slug in affected:
  row=by[slug]
  for field,value in [('operating_status','current or seasonally current'),('rv_access',True),('reservation_method',row['Reservation window']),('hookups',int(row['Hookups']))]:
   evidence['observations'].append({'slug':slug,'field':field,'status':'supported','checked_on':CHECKED,'summary':f'Current county material supports {field.replace("_"," ")}.','proposed_value':value,'source_family':'snohomish-county-review','sources':[source(urls[slug],'Current operator facility details and campground inventory support the published value.'),source(COUNTY,'County campground inventory supports system-wide utilities, seasons, and policies.')]})
  max_value=int(row['Max RV length']) if row['Max RV length'] else None
  max_summary='Current operator page publishes the campground-wide maximum.' if max_value else 'Current operator material does not publish one campground-wide maximum; the public record intentionally directs users to site-specific dimensions.'
  evidence['observations'].append({'slug':slug,'field':'max_rv_length','status':'supported','checked_on':CHECKED,'summary':max_summary,'proposed_value':max_value,'source_family':'snohomish-county-review','sources':[source(urls[slug],'Operator material supports the published maximum or the explicit decision to leave it unclaimed.')]})
 corrections={'flowing-lake-county-park':['RV count corrected to 39 confirmed utility sites','97-acre lake claim corrected to 132.5 acres','unsupported universal 35-foot limit narrowed to fifth-wheels','unsupported rental claim removed','unsupported naturally reproducing trout claim removed'],'kayak-point-regional-park':['unsupported universal 35-foot limit removed','pier corrected from 700 to 300 feet','unsupported water-view claim removed','unsupported nesting and daily wildlife claims removed','current construction and playground closure added'],'wenberg-county-park':['shore corrected from north to east','unsupported universal 45-foot limit removed','unsupported warm-water and comfortable-swimming claims removed','unnecessary Costco proximity claim removed']}
 for slug,items in corrections.items():
  scrub_sources=[source(urls[slug],'Current operator page supports the corrected record.')]
  if slug=='flowing-lake-county-park': scrub_sources.append(source(FLOW_MAP,'Current campground map supports the utility-site count and preserves the conflict with the facility-page total.'))
  evidence['observations'].append({'slug':slug,'field':'content_scrub','status':'corrected_locally','checked_on':CHECKED,'summary':'; '.join(items)+'.','proposed_value':items,'source_family':'snohomish-county-review','sources':scrub_sources})
 EVIDENCE.write_text(json.dumps(evidence,indent=2)+'\n')
 print(f'Completed Snohomish County phase: added {len(NEW)} campgrounds and corrected 14 unique factual issues across {len(updates)} existing records. Dataset now has {len(rows)} records.')

if __name__=='__main__': main()
